### ISSUE TITLE
libphonenumber-js Metadata parsing issue

### ISSUE THREAD

**Issue by Aman725** [halt-hammerzeit/react-phone-number-input#4]
I know this may not be directly related to react-phone-number-input but i am not able to use this component as such, however can you suggest me some fix. 
node version : 6.9.2
npm version: 3.10.9
This is the error i am getting. 

ERROR in ./~/libphonenumber-js/metadata.min.json
Module parse failed: C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\libphonenumber-js\metadata.min.json Unexpected token (1:34)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:34)
    at Parser.pp$4.raise (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\Aman\WebstormProjects\kredx-fe\client\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/libphonenumber-js/index.common.js 3:15-40

**Comment by halt-hammerzeit** [comment]
Yes, it's not related to this, because 
> Module parse failed: You may need an appropriate loader to handle this file type.

Is a Webpack error, and it tells you that you don't have `json-loader` set up (for Webpack 1).
Webpack 2 has `json-loader` set up by default.

**Comment by halt-hammerzeit** [comment]
See the updated readme (Webpack section)
